version: "3.9"

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=test_user
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=test_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - db

